### ISSUE TITLE
可以考虑换女队logo标志

### ISSUE THREAD

**Issue by tangent1231** [XCPCIO/board#14]
现在女队的标志和厕所的标志一样，可以清晰的看到这个是女队，不过可以尝试换一些logo
https://www.iconfont.cn/search/index?searchType=icon&q=%E9%B2%9C%E8%8A%B1&page=1&fromCollection=1&fills=&tag=
可以试试粉色的花朵

替换效果：
![5d8dfdd784afdeae09f2153ab9e112d](https://github.com/XCPCIO/board/assets/41216851/dcfb55ee-9fb1-466d-8ab4-1aeabd2cf42a)

**Comment by Dup4** [comment]
complete with #18
